### PR TITLE
Added contact card

### PR DESCRIPTION
**Pull request by AbhishekJadhav2002**

### CODE REVIEW

**Comment by AbhishekJadhav2002** [comment]
@mukulbbhardwaj will you check my contribution and provide the feedback.

**Comment by mukulbbhardwaj** [comment]
> @mukulbbhardwaj will you check my contribution and provide the feedback.

Add a deployed link or atleast add an image showing what you build.

**Comment by AbhishekJadhav2002** [comment]
> > @mukulbbhardwaj will you check my contribution and provide the feedback.
> 
> Add a deployed link or atleast add an image showing what you build.

Sorry for the inconvenience caused !
Here is the screenshot of the work done in this PR -
Screenshot

**Comment by mukulbbhardwaj** [comment]
> > > @mukulbbhardwaj will you check my contribution and provide the feedback.
> > 
> > 
> > Add a deployed link or atleast add an image showing what you build.
> 
> Sorry for the inconvenience caused ! Here is the screenshot of the work done in this PR - Screenshot

Good work merging it.

**Pull request merged**
